server:
  port: 8080


spring:
  application:
    name: managesys

  datasource:
    name: managesys-DBCP
    url: jdbc:mysql://127.0.0.1:3306/managesys?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      connectionTimeout: 50000
      idleTimeout: 600000
      maxLifetime: 3600000
      validationTimeout: 5000
      leakDetectionThreshold: 20000
      maximumPoolSize: 20
      minimumIdle: 20

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 2000
    pool:
      max-active: 1024
      max-idle: 200
      max-wait: 1000
      min-idle: 200
      testOnBorrow: true
      testOnReturn: true

  http:
    multipart:
      max-file-size: 12mb
      max-request-size: 24mb

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com/jj/managesys/domain